### ISSUE TITLE
Install fails with "package not found errors"

### ISSUE THREAD

**Issue by frost19k** [mihirlad55/LadOS#12]
Initially Install was failing because of the `/install/rankmirrors` script. 
It would wipe out my `/etc/pacman.d/mirrorlist` file. 
I mean `cat /etc/pacman.d/mirrorlist` had no output. 

![Screenshot from 2021-08-20 04-58-56](https://user-images.githubusercontent.com/49780407/130156826-d2b12a35-3148-484e-a358-91ffbf13368a.png)

Installation continued after deleting the function call in `/install/install.sh` & refreshing the mirrorlist manually with reflector. 

I'm not sure which stage this is failing at. The script asked me for root password & default user account. 

![Screenshot from 2021-08-20 04-42-48](https://user-images.githubusercontent.com/49780407/130156570-ea9baded-3406-48b8-8c7f-853b3d181960.png)

**Comment by mihirlad55** [comment]
Sorry for the very late response, it's been very busy. This error arose when Arch Linux changed some things with their URLs. However, there is a simple fix for this that hasn't been merged into master yet. This was fixed in commit 5882ee17f857d4f109947bf0c261304ffd922b0a.
